replicaCount: 1

image:
  repository: your-dockerhub-username/api-txt2audio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.example.com
      secretName: api-txt2audio-tls

gpu:
  enabled: false  # Mettre à true pour activer le GPU
  count: 1        # Nombre de GPU à allouer
