include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"
  PYTHON_VERSION: "3.11"           # déjà présent chez toi
  TORCH_CUDA_ARCH_LIST: "9.0"  # A100 + H100 (ajuste si besoin)

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build-app:
  stage: docker-build
  extends:
    - .kaniko:build-push
  variables:
    WORKING_DIR: "."
    DOCKERFILE: "Dockerfile"
    IMAGE_NAMES: >
      ${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
      ${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
    EXTRA_BUILD_ARGS: >
      --target runtime
      --build-arg PYTHON_VERSION=${PYTHON_VERSION}
      --build-arg TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}
