variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"
  PYTHON_VERSION: "3.12"
  TORCH_CUDA_ARCH_LIST: "9.0"  # OK même si ignoré (aucune compile)

  # >>> Réservations pour éviter TerminationByKubelet
  KUBERNETES_MEMORY_REQUEST: "8Gi"   # ou 10Gi si nœuds costauds
  KUBERNETES_MEMORY_LIMIT:   "16Gi"  # ≥ 14–16Gi (pic ~12.6Gi)
  KUBERNETES_CPU_REQUEST:    "2"
  KUBERNETES_CPU_LIMIT:      "4"

docker-build-app:
  stage: docker-build
  extends:
    - .kaniko:build-push
  variables:
    WORKING_DIR: "."
    DOCKERFILE: "Dockerfile"
    IMAGE_NAMES: >
      ${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
      ${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
    EXTRA_BUILD_ARGS: >
      --build-arg PYTHON_VERSION=${PYTHON_VERSION}
      --build-arg TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}
    # Si ton template expose KANIKO_ARGS (ou EXTRA_ARGS), utilise :
    KANIKO_ARGS: >
      --snapshotMode=redo
      --cache=true
      --cache-copy-layers
      --verbosity=info
