include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"

  PYTHON_VERSION: "3.12"
  TORCH_CUDA_ARCH_LIST: "9.0"

  # Ressources pod CI (pic ~13Gi observé)
  KUBERNETES_MEMORY_REQUEST: "10Gi"
  KUBERNETES_MEMORY_LIMIT:   "16Gi"
  KUBERNETES_CPU_REQUEST:    "2"
  KUBERNETES_CPU_LIMIT:      "4"

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build-app:
  stage: docker-build
  extends:
    - .kaniko:build-push
  variables:
    WORKING_DIR: "."
    DOCKERFILE: "Dockerfile"
    IMAGE_NAMES: >
      ${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
      ${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}

    # ⚠️ Pas d'antislashs, tout sur une ligne (utilise >-)
    EXTRA_BUILD_ARGS: >-
      --build-arg PYTHON_VERSION=${PYTHON_VERSION} --build-arg TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}

    # Selon ton template : EXTRA_KANIKO_ARGS (ou KANIKO_ARGS). Garde UNE clé seulement.
    EXTRA_KANIKO_ARGS: >-
      --snapshotMode=redo --cache=true --cache-copy-layers --verbosity=info
