{{- if or .Values.app.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "helper.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "helper.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.app.secrets -}}
  {{- include "helper.secret" .Values.app | indent 2 }}
  {{- end -}}
{{- end -}}
