{{- if .Values.app.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helper.serviceAccountName" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
{{- end }}
