{{- range $index, $vss := .Values.vaultStaticSecrets }}
{{- if $vss.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ printf "%s-%s-%s" (include "helper.fullname" $) "vss" ($index | toString) }}
  labels:
    {{- include "helper.labels" $ | nindent 4 }}
    {{- with $vss.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $vss.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $vss.namespace }}
  namespace: {{ . }}
  {{- end }}
  mount: {{ $vss.mount }}
  vaultAuthRef: {{ $vss.vaultAuthRef }}
  path: {{ $vss.path }}
  {{- with $vss.version }}
  version: {{ . }}
  {{- end }}
  type: {{ $vss.type | default "kv-v2" }}
  {{- with $vss.refreshAfter }}
  refreshAfter: {{ . }}
  {{- end }}
  hmacSecretData: {{ $vss.hmacSecretData | default true }}
  {{- with $vss.rolloutRestartTargets }}
  rolloutRestartTargets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- $destination := default (dict) $vss.destination }}
  destination:
    create: {{ default true $destination.create }}
    overwrite: {{ default false $destination.overwrite }}
    {{- with $destination.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $destination.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    name: {{ default (printf "%s-%s-%s" (include "helper.fullname" $) "vss" ($index | toString)) $destination.name }}
    type: {{ default "Opaque" $destination.type }}
    {{- with $destination.transformation }}
    transformation:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
